version: '3.8'

services:
  ingestion-service:
    build: .
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ingestion-db:5432/ingestion_db
      - DOCUMENT_SERVICE_URL=http://document-service:8000
      - SEARCH_SERVICE_URL=http://search-service:8000
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AUTH_SERVICE_URL=http://auth-service:8000
    volumes:
      - ./:/app
    depends_on:
      - ingestion-db
      - redis
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  ingestion-worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ingestion-db:5432/ingestion_db
      - DOCUMENT_SERVICE_URL=http://document-service:8000
      - SEARCH_SERVICE_URL=http://search-service:8000
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AUTH_SERVICE_URL=http://auth-service:8000
    volumes:
      - ./:/app
    depends_on:
      - redis
      - ingestion-service
    command: celery -A src.core.worker worker --loglevel=info

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - ingestion-worker
    command: celery -A src.core.worker flower --port=5555

  ingestion-db:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ingestion_db
    volumes:
      - ingestion-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  ingestion-db-data:
  redis-data: 